services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    entrypoint: /opt/jenkins/scripts/jenkins-entrypoint.sh
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/jenkins/scripts/:/var/jenkins_home/init.groovy.d
      - /opt/jenkins/scripts/jenkins-entrypoint.sh:/opt/jenkins/scripts/jenkins-entrypoint.sh
    user: root

volumes:
  jenkins_home: